apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mushop-test
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    cert-manager.io/acme-challenge-type: http01
spec:
  tls:
  - secretName: mushop-test-tls
    hosts:
    - test.mushop.ateam.cloud
  rules:
  - host: test.mushop.ateam.cloud
    http:
      paths:
      - path: /
        backend:
          serviceName: edge
          servicePort: 80
