apiVersion: extensions/v1
kind: Ingress
metadata:
  name: mushop-dev
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: edge
          servicePort: 80
